<?php
if(isset($_GET["anoLetivo"]) && !empty($_GET["anoLetivo"]))
	$anoLetivo = $_GET["anoLetivo"];
?>
<h2>Boletim</h2>
<div>
		<div class="tabelaBoletim">
			<fieldset style="margin-top: 10px;">
				<legend><strong>Visualizando:</strong> - <?php echo $this->boletim['ano']; ?> </legend>
				<?php ;
           echo $this->tabela;
          ?>
				
			</fieldset>
			<div style="margin-top:15px;"><strong>Outros anos:</strong>
			<select name="outrosAnos" onchange="carregar('ajaxPage','boletim.php?anoLetivo='+this.value)">
				<option selected="selected">Selecione...</option>
        <?php foreach ($this->dados_aluno['matriculas'] as $key => $matricula){ ?>
           <option value="<?php echo $matricula['cod_matricula']; ?>"><?php echo $key; ?></option>
			  <?php } ?>
			</select></div>
		</div>

	</div>
