
<?php echo $this->render('titulo.phtml'); ?>

<div id="sys_conteudo">

    <div id ="painel_principal">

        <div id="cpanel">

		<div style="float:left;">
			<div class="icon">
				<a href="<?php echo BASE_URL.'/admin/configws'; ?>">
                                    <img alt=""  src="<?php echo BASE_URL.'/public/templates/system/imagens/config2.png'; ?>" align="middle" border="0" />
                                            <span>Config. Webservice</span>
                                </a>
                        </div>
		</div>

	  </div>
    </div>
</div>