<script type='text/javascript'>
	$(document).ready(function (){

    function carregar(local,url){
       $(local).load(url);
    }

    $('#ajaxcontent').ajaxStart(function(){
       $('#carregando').css('display','block');
       $('#ajaxcontent').css('display','none');
    });
    
    $('#ajaxcontent').ajaxStop(function(){
       $('#carregando').css('display','none');
       $('#ajaxcontent').css('display','block');
    });

    $('#meusdados').click(function(e){
      e.preventDefault();
      carregar('#ajaxcontent','<?php echo $this->baseUrl;?>/meusdados');
  
    });

    $('#boletim').click(function(e){
      e.preventDefault();
      carregar('#ajaxcontent','<?php echo $this->baseUrl;?>/boletim');
    });

     $('#meusdocumentos').click(function(e){
      e.preventDefault();
      carregar('#ajaxcontent','<?php echo $this->baseUrl;?>/meusdocumentos');
    });
     //Executa após carregar a pagina
     carregar('#ajaxcontent','<?php echo $this->baseUrl;?>/index/ajax');
  });
</script>

<div style="height:20px;"></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="menuAluno">
	<tr>
		<td width="35%" align="center"><a href="#" id="boletim" ><img src="<?php  echo $this->placeholder('baseUrlPath')?>/templates/<?php  echo $this->placeholder('template-site')?>/imagens/boletim.png" width="128" height="128" alt="Boletim" /><br />Boletim</a></td>
		<td width="35%" align="center"><a href="#" id="meusdocumentos"><img src="<?php  echo $this->placeholder('baseUrlPath')?>/templates/<?php  echo $this->placeholder('template-site')?>/imagens/documentos.png" width="128" height="128" alt="Documentos" /><br/>Meus Documentos</a></td>
		<td width="30%" align="center"><a  id="meusdados" href="#" ><img src="<?php  echo $this->placeholder('baseUrlPath')?>/templates/<?php  echo $this->placeholder('template-site')?>/imagens/conta.png" width="128" height="128" alt="Mesus Dados" /><br />Meus Dados</a></td>
	</tr>
</table>
<div style="height:10px;"></div>

<div id="ajaxcontent"></div>
