<?php
if(isset($this->option)){ ?>
    <script type='text/javascript'>
	$(document).ready(function (){

            var val = '<?php echo $this->option['id'];  ?>';
            var text = '<?php echo $this->option[$this->field]; ?>';
            
            $('<?php echo $this->selectId; ?>').append("<option value='"+val+"' selected='selected'>"+text+"</option>");
            $('#dialog-add').html("");
            $('#dialog-add').dialog("close");
       });
</script>
<?php } else { ?>
<script type='text/javascript'>
	$(document).ready(function (){

             $('.salvar').click(function(){
                 var url = $('#formbox').attr('action');
                 $.post(url, $('#formbox').serialize(),
                    function(data){
                    $('#dialog-add').html(data);
                  },
                'html');
                        
            });

             $('.cancelar').click(function(){

			$('#dialog-add').dialog("close");

            });



       });
</script>

<?php echo $this->render('titulo.phtml'); ?>



<div id="sys_conteudo">
    <div class="sub_titulo"><?php echo $this->infoForm;?></div>
    <div class="conteudo_form">
        
        <?php echo $this->form; ?>
    </div>
</div>
<div id='conteiner_tool'>
    <div id='tool'>
            <ul>
                <li><a class='salvar' href='#'>Salvar</a></li>
                <li><a class='cancelar' href='#'>Cancelar</a></li>
            </ul>

    </div>
    
</div>

<?php } ?>
