<h2>Meus Dados</h2>
<fieldset>
	<legend>Dados Básicos - <a href="#" target="_blank">Gerar PDF</a> | <a href="#" target="_blank">Imprimir</a></legend>
	<table width="100%" border="0" cellspacing="0" cellpadding="3">
		<tr>
			<td width="12%" align="right"><strong>Nome:</strong></td>
			<td width="88%"><?php echo $this->convertUTF8($this->dados_aluno['nome']); ?></td>
		</tr>
		<tr>
			<td align="right"><strong>Responsável:</strong></td>
			<td><?php echo $this->convertUTF8($this->dados_aluno['reponsavel_aluno']); ?></td>
		</tr>
	</table>

  <?php foreach ($this->dados_aluno['matriculas'] as $key => $matricula){ ?>
	<fieldset style="margin-top:10px;">

		<legend>Matrícula - Ano  <?php echo $key; ?></legend>
		<table width="100%" border="0" cellspacing="0" cellpadding="3">
			<tr>
				<td width="11%" align="right"><strong>Instituição:</strong></td>
				<td width="89%"> <?php echo $this->convertUTF8($matricula['nm_escola']); ?></td>
			</tr>
			<tr>
				<td align="right"><strong>Curso:</strong></td>
				<td><?php echo $this->convertUTF8($matricula['nm_curso']); ?></td>
			</tr>
			<tr>
				<td align="right"><strong>Série:</strong></td>
				<td><?php echo $this->convertUTF8($matricula['nm_serie']); ?></td>
			</tr>
      <tr>
				<td align="right"><strong>Turma:</strong></td>
				<td><?php echo $this->convertUTF8($matricula['nm_turma']); ?></td>
			</tr>
       <tr>
				<td align="right"><strong>Situação:</strong></td>
				<td><?php echo $this->convertUTF8($matricula['situacao']); ?></td>
			</tr>
		</table>
	</fieldset>
  <?php } ?>
</fieldset>