<div style="height: 50px;"></div>
<div id="login_conteiner" >
  <h2 align="center">Informe seu Login e Senha para continuar</h2>
  <?php if(isset($this->erro_login)) {?>
       <div class="error"><?php echo $this->erro_login?></div>
  <?php } ?>
<div id="login_form">
  <form action="" enctype="application/x-www-form-urlencoded" method="post" class="formLogin">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="28%" align="right"><label for="login">Login:</label></td>
        <td ><input type="text" name="login" id="login" /></td>
      </tr>
      <tr>
        <td align="right"><label for="senha">Senha:</label></td>
        <td ><input type="password" name="senha" id="senha" /></td>
      </tr>
      <tr>
        <td >&nbsp;</td>
        <td ><input id ="login_submit"type="submit" value="Enviar" />&nbsp;&nbsp;<input id ="login_reset" type="reset" value="Limpar" /></td>
      </tr>
    </table>
  </form>
</div>
</div>