<h2 align="center">Informe seu Login e Senha para continuar</h2>
  <?php if(isset($this->erro_login)) {?>
       <div class="erro"><?php echo $this->erro_login?></div>
  <?php } ?>
<form action="" enctype="application/x-www-form-urlencoded" method="post" class="formLogin">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="44%" align="right"><label for="login">Login:</label></td>
        <td width="56%"><input type="text" name="login" id="login" /></td>
      </tr>
      <tr>
        <td width="44%" align="right"><label for="senha">Senha:</label></td>
        <td width="56%"><input type="password" name="senha" id="senha" /></td>
      </tr>
      <tr>
        <td width="44%">&nbsp;</td>
        <td width="56%"><input type="reset" value="Limpar Dados" />&nbsp;&nbsp;<input type="submit" value="Enviar" /></td>
      </tr>
    </table>
</form>