<h2>Meus Documentos</h2>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td width="35%" align="center" valign="top">
			<img src="<?php  echo $this->placeholder('baseUrlPath')?>/templates/<?php  echo $this->placeholder('template-site')?>/imagens/page_go.png" alt="" width="32" height="32" /><br />
			<strong>Boletim</strong> (atual)<br />
			<a href="#">baixar</a> | <a href="#">visualizar / imprimir</a>
		</td>
		<td width="30%" align="center" valign="top">
			<img src="<?php  echo $this->placeholder('baseUrlPath')?>/templates/<?php  echo $this->placeholder('template-site')?>/imagens/comprovante_matricula.png" alt="" width="32" height="32" /><br />
			<strong>Comprovante de Matrícula</strong><br />
			<a href="#">baixar</a> | <a href="#">visualizar / imprimir</a>
		</td>
		<td width="35%" align="center" valign="top">
			<img src="<?php  echo $this->placeholder('baseUrlPath')?>/templates/<?php  echo $this->placeholder('template-site')?>/imagens/grade_curricular.png" alt="" width="32" height="32" /><br />
			<strong>Grade Curricular</strong><br />
			<a href="#">baixar</a> | <a href="#">visualizar / imprimir</a>
		</td>
	</tr>
</table>
